config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  devise_for :users

  resources :books do
    resources :reviews, only: %i[new create]
  end

  root to: "books#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/author.rb
class Author < ApplicationRecord
  has_and_belongs_to_many :books

end

app/models/book.rb
class Book < ApplicationRecord
  has_and_belongs_to_many :authors
  has_many :reviews

  validates :title, presence: true

  scope :pageorder, -> { order('pages DESC') }
  scope :with_pages, ->(min, max) { where('pages >= ? AND pages <= ?', min, max) }
  scope :living_writers, ->{ joins(:authors).where('dod is ?', nil).uniq }
  scope :with_good_reviews, ->(rating) { joins(:reviews).group(:book_id).having('AVG(stars) >= ?', rating) }
  scope :books_by, ->(name) { joins(:authors).where('name LIKE ?', "%#{name}%") }

  def self.title_search(string)
    Book.where("title like ?", "%#{string}%")
  end
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :book
  belongs_to :review_author

  validates :stars, numericality: {only_integer: true, in: 1..5}
end

app/models/review_author.rb
class ReviewAuthor < ApplicationRecord
  has_many :reviews
  has_many :books, through: :reviews
  belongs_to :user

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_one :review_author
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!, only: %i[new create edit update]

  def index
    searchfield = params[:title_search]
    @books = if params[:title_search]
      Book.title_search(searchfield)
    else
      Book.all.order(:title) # order(title: :desc)
    end
  end

  def show
    @book = Book.find(params[:id])
    @reviews = @book.reviews
  end

  def new
    @book = Book.new
  end

  def create
    @book = Book.new(create_update_params)
    if @book.save
      flash[:notice] = "#{@book.title} successfully created"
      redirect_to books_path and return
    else
      flash[:alert] = "Creation failed"
      render 'new', status: :unprocessable_entity
    end
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(create_update_params)
      flash[:notice] = "#{@book.title} successfully updated"
      redirect_to book_path(@book) and return
    else
      flash[:alert] = "Update failed"
      render 'edit', status: :unprocessable_entity
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    flash[:alert] = "Book '#{@book.title}' deleted."
    redirect_to books_path
  end

  private
  def create_update_params
    params.require(:book).permit(:title, :publisher, :year, :pages, :list_price)
  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :authenticate_user!

  def new
    # book_id because of nested route
    @book = Book.find(params[:book_id])
    @review = Review.new
  end

  def create
    # book_id because of nested route
    @book = Book.find(params[:book_id])
     # build sets the book foreign key automatically
    @review = @book.reviews.build(create_update_params)
    @review.review_author = current_user.review_author
    if @review.save
      flash[:notice] = 'Review successfully created.'
      redirect_to(book_path(@book))
    else
      flash[:alert] = 'Failure to create new review.'
      render :new, status: :unprocessable_entity
      # redirect_to(new_book_review_path(@book))
    end
  end

  private
  def create_update_params
    params.require(:review).permit(:stars, :review)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/books/_book.html.erb
      <tr>
        <td><%= link_to book.title, book_path(book) %>
        <td><%= book.publisher %>
        <td><%= book.year %>
        <td><%= book.pages %>
        <td><%= number_to_currency(book.list_price) %>
      </tr>

app/views/books/_form_template.html.erb
  <% if @book.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@book.errors.count, "error") %> prevented
        this book from being saved:
      </h2>
      <ul>
        <% @book.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= book_form.label :title %>
  <%= book_form.text_field :title %>
  <br>

  <%= book_form.label :publisher %>
  <%= book_form.text_field :publisher %>
  <br>

  <%= book_form.label :year %>
  <%= book_form.number_field :year %>
  <br>

  <%= book_form.label :pages %>
  <%= book_form.number_field :pages %>
  <br>

  <%= book_form.label :list_price %>
  <%= book_form.number_field :list_price, step: 0.01 %>
  <br>

  <%= book_form.submit %>

app/views/books/edit.html.erb
<div class="container">
<%# in app/views/books/edit.html.erb %>
<%= form_with model: @book, method: :put do |book_form| %>

  <%= render partial: 'form_template', locals: {book_form: book_form} %>

<% end %>
</div>

app/views/books/index.html.erb
<section>
<div class="container">
<div class="searchbox">
  <%= form_with url: books_path, local: true, method: :get do %>
  <%= label_tag "title_search" %>
  <%= text_field_tag "title_search", nil, maxlength: 10 %>
  <%= submit_tag "Search", class: "btn btn-primary" %>
  <%= link_to "Reset", books_path, class: "btn btn-dark" %>
  <% end %> 
</div>

  <table class="table">
    <thead>
      <tr>
        <th>Title
        <th>Publisher
        <th>Release year
        <th>Pages
        <th>Price
      </tr>
    </thead>
    <tbody>
      <%= render partial: 'book', collection: @books %>
    </tbody>
  </table>
  <br>
  <% if user_signed_in? && current_user.admin %>
    <%= link_to "Create new book", new_book_path, class: "btn btn-secondary" %>
  <% end %>
  </div>
</section>

app/views/books/new.html.erb
<div class="container">
<%# in app/views/books/new.html.erb %>
<%= form_with model: @book do |book_form| %>

  <%= render partial: 'form_template', locals: {book_form: book_form} %>

<% end %>
</div>

app/views/books/show.html.erb
<section>
<div class="container">
  <h1>Details for <%= @book.title %></h1>
  <dl>
  <dt>Publisher</dt>
  <dd><%= @book.publisher %></dd>
  <dt>Year</dt>
  <dd><%= @book.year %></dd>
  <dt>Pages</dt>
  <dd><%= @book.pages %></dd>
  <dt>Price</dt>
  <dd><%= number_to_currency(@book.list_price) %></dd>
  </dl> 
  <br>

  <% if user_signed_in? && current_user.admin %>
    <%= link_to "Edit book", edit_book_path(@book), class: "btn btn-info" %>
    <%= button_to "Delete book", book_path(@book), method: :delete, class: "btn btn-warning" %>
  <% end %>
<div>

  <div class="container">
    <table class="table">
      <thead>
        <tr>
          <th>Rating</th>
          <th>Review</th>
          <th>By</th>
        </tr>
      </thead>
      <tbody>
  <%= render collection: @reviews, partial: 'reviews/review' || "No reviews yet" %>
      </tbody>
    </table>
    <%if user_signed_in? %>
      <%= link_to "Write a new review", new_book_review_path(@book), class: "btn btn-secondary" %>
    <% end %>
  </div>
  <%= link_to "Back to index", books_path, class: "btn btn-primary" %>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Testapp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
        <section id="auth" class="container">
      <% if user_signed_in? %>
        <div class="row alert alert-dark">
          <div class="col-md-10">
            <p> Hello, <%= current_user.email %></p>
          </div>
          <div class="col-md-2">
            <%= button_to "Sign out", destroy_user_session_path, method: :delete, class: "btn btn-warning" %>
          </div>
        </div>
      <% else %>
        <div class="row alert alert-dark">
          <div class="col-md-10">
            <p> Hello, guest</p>
          </div>
          <div class="col-md-2">
            <%= link_to "Sign in", new_user_session_path, class: "btn btn-primary" %>
          </div>
        </div>
      <% end %>
    </section>

        <section id="flash" class="container">
  <% if flash[:notice] %>
  <div class="alert alert-primary">
    <%= "#{flash[:notice]}" %> 
  </div>
<% end %>

<% if flash[:alert] %>
  <div class="alert alert-warning">
    <%= "#{flash[:alert]}" %>
  </div>
<% end %>
        </section>

    <%= yield %>
  </body>
</html>

app/views/reviews/_review.html.erb
<tr>
  <td><%= review.stars %>
  <td><%= review.review %>
  <td><%= review.review_author.user.email %>
</tr>

app/views/reviews/new.html.erb
<%= form_with model: @review, url: book_reviews_path(@book), method: :post do |f| %>
  <div class="field">
    <%= f.label :stars, "Stars" %>
    <%= f.number_field :stars, :in => 1..5 %>
  </div>
  <div class="field">
    <%= f.label :review, "Review" %>
    <%= f.text_field :review %>
  </div>
  <br>
  <%= f.submit "Submit review" %>
  <br>
<% end %>

<%= link_to 'Back to book details', book_path(@book) %>